# NumPy exercises

We are going to practice NumPy skills and basic syntax.

We put here also some examples that were not in the tutorial on purpose. Try to use google and offial NumPy documentation to solve these exercises.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [5]:
x = np.zeros(10)
x[5] = 1
print(x)

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [10]:
v = np.arange(10,50)
print(v)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [16]:
reversed_v = v[::-1]
print (reversed_v)


[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [22]:
x =  np.arange(0, 9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [27]:
a=np.array([1,2,0,0,4,0])
print(a)
np.nonzero(a)

[1 2 0 0 4 0]


(array([0, 1, 4], dtype=int64),)

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [30]:
x = np.random.random((3,3,3))
print(x)

[[[0.18226844 0.52184348 0.53270046]
  [0.2943856  0.22810132 0.57294111]
  [0.52462395 0.84723144 0.90858075]]

 [[0.17242551 0.27088933 0.16948595]
  [0.94526482 0.86211293 0.8724725 ]
  [0.11698352 0.66377155 0.39377844]]

 [[0.62612007 0.95882206 0.75430218]
  [0.38941611 0.77232582 0.9499588 ]
  [0.52402679 0.70974022 0.12241257]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [53]:
x=np.random.randint(1000000, size=(10,10))
print(x)

mn=np.min(x)
mx=np.max(x)
print(mn)
print(mx)

[[465151 486490 457000 374508 145406 871236 953761  45635 192981 592102]
 [896381 213845  33626 522793 870146 652692  47951 477054 872531 522756]
 [288066 179429  71756 904777 247574 772276 307029 181347 170460  65095]
 [184142 969090 999113  88094 611040 380136 983316 330861 684654 714230]
 [608433  49985 789534  83736 947248  88619 874934 608115 914182 275670]
 [762238 945686 789794 747850  49725 974747 148287 134299 683937 309208]
 [487763  53958 722120  52045 589441 524291 380460 426191 522550 902598]
 [347577 371785 532449  24699 642441 328401  76033 547587 187787 414941]
 [752215 255595 767303 602153 866666 224530 311461 714592 406409 494021]
 [721783   8691 713828 998534 394915  54282 191189  58135 193148 421190]]
8691
999113


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [62]:
x=np.random.randint(1000000, size=(30))
print(x)

m=np.mean(x) 
print(m)

[555440 765296 463291 134834 814933 812892  51551 935426 871066 576808
 658330 683902 870240  51422 349375 907122 507071 630042   3756 120219
 671377 552010 584627 752030 681609 321365 490785 785621 947681 164453]
557152.4666666667


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [65]:
x = np.ones((3,3))
x[1:-1,1:-1] = 0
print(x)

[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [66]:
x = np.ones((3,3))
x = np.pad(x, pad_width=1, mode='constant', constant_values=0)
print(x)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [92]:
nan
False
False
nan
False

NameError: name 'nan' is not defined

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [68]:
Z = np.diag(1+np.arange(4), k = -1)
print (Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [69]:
print (np.unravel_index(100, (6,7,8)))


(1, 5, 4)


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [74]:
x= np.random.random((3,3))
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
print(x)

[[0.76704678 0.92634155 0.76508528]
 [0.25757748 0.         0.92324673]
 [0.75996907 1.         0.79479864]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [84]:
x=np.array([1,2,3,4,5,6,7,8,9,10,11])

x[3:9] = np.multiply(x[3:9],-1)

print(x)

[ 1  2  3 -4 -5 -6 -7 -8 -9 10 11]


#### 29. How to round away from zero a float array ? (★☆☆)

#### 30. How to find common values between two arrays? (★☆☆)

In [91]:
x = np.array([0, 10, 20, 40, 60])
y = [10, 30, 40]

print(np.intersect1d(x, y))

[10 40]


#### 32. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [93]:
def generate(): 
    for x in range(10):
        yield x
        
Z = np.fromiter(generate(), dtype=float, count=-1)
print (Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [94]:
Z = np.linspace(0,1,12,endpoint=True)[1:-1]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [95]:
Z = np.random.random(10)
Z.sort()
print(Z)

[0.00761517 0.11148501 0.23119829 0.23323095 0.32712837 0.51983742
 0.58587623 0.69722922 0.75053304 0.95958473]


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [98]:
x = np.random.randint(0,2,6)
print(x)
y = np.random.randint(0,2,6)
print(y)

array_equal = np.allclose(x, y)
print(array_equal)

[0 1 0 0 0 1]
[0 1 1 0 0 0]
False


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [99]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.         0.33618214 0.07105232 0.40718564 0.46573569 0.14434984
 0.49406717 0.56268712 0.59492554 0.32278783]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [100]:
x = np.arange(100)
print("Original array:")
print(x)
a = np.random.uniform(0,100)
print("Value to compare:")
print(a)
index = (np.abs(x-a)).argmin()
print(x[index])

Original array:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
Value to compare:
28.773438373673677
29


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [101]:
Z = np.arange(10, dtype=np.int32)
Z = Z.astype(np.float32, copy=False)

#### 59. How to sort an array by the nth column? (★★☆)

In [107]:
a = np.array([[9, 2, 3],[4, 5, 6],[7, 0, 5]])
print(a)
#sort by second column
a[a[:,1].argsort()]

[[9 2 3]
 [4 5 6]
 [7 0 5]]


array([[7, 0, 5],
       [9, 2, 3],
       [4, 5, 6]])

#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [108]:
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

False


#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [109]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 72. How to swap two rows of an array? (★★★)

In [115]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14],[15,16,17,18,19,20,21]])
a[[0, 2]] = a[[2, 0]]
print(a)

[[15 16 17 18 19 20 21]
 [ 8  9 10 11 12 13 14]
 [ 1  2  3  4  5  6  7]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [116]:
Z = np.random.randint(0,2,100)
print ('original: ')
print (Z)
print('Negating a boolean: ')
print(np.logical_not(Z, out=Z))

original: 
[0 1 1 0 1 0 1 1 0 0 1 1 0 1 0 1 1 0 1 1 1 0 0 0 1 1 1 1 1 0 0 0 1 1 0 1 0
 0 1 1 0 0 0 0 0 1 0 0 1 1 1 1 0 1 1 0 0 1 0 0 0 0 1 1 0 0 1 1 1 1 1 0 1 0
 0 1 1 0 1 0 1 1 1 1 0 1 0 1 1 1 1 1 0 0 0 1 1 0 0 0]
Negating a boolean: 
[1 0 0 1 0 1 0 0 1 1 0 0 1 0 1 0 0 1 0 0 0 1 1 1 0 0 0 0 0 1 1 1 0 0 1 0 1
 1 0 0 1 1 1 1 1 0 1 1 0 0 0 0 1 0 0 1 1 0 1 1 1 1 0 0 1 1 0 0 0 0 0 1 0 1
 1 0 0 1 0 1 0 0 0 0 1 0 1 0 0 0 0 0 1 1 1 0 0 1 1 1]


#### 83. How to find the most frequent value in an array?

In [117]:
Z = np.random.randint(0,10,50)
print (Z)
print('rank:', np.bincount(Z).argmax())

[9 7 5 5 5 4 1 4 8 3 7 7 7 5 0 2 1 0 9 9 9 4 0 2 2 7 6 8 3 7 4 0 3 6 4 6 3
 2 5 1 9 9 5 4 6 3 9 8 5 8]
rank: 5


#### 89. How to get the n largest values of an array (★★★)

In [119]:
import numpy as np
x = np.arange(10)
print("Original array:")
print(x)
np.random.shuffle(x)
n = 1
print (x[np.argsort(x)[-n:]])

Original array:
[0 1 2 3 4 5 6 7 8 9]
[9]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [120]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

[[0 0 1]
 [1 0 0]
 [1 0 1]]
