In [2]:
import numpy as np

In [3]:
a = np.array([1,3,5])

In [4]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])

In [5]:
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [6]:
a*b

array([[ 9., 24., 35.],
       [ 6., 15., 20.]])

In [13]:
# Get Dimension
a.ndim

1

In [14]:
# Get Dimension
b.ndim

2

In [18]:
#Get shape
b.shape

(2, 3)

In [22]:
# Get Type
a.dtype

dtype('int32')

In [23]:
# Get size:
a.itemsize


4

In [25]:
# Get total size: (in bytes)
a.size * a.itemsize


12

In [26]:
# Get total size: (in bytes)
a.nbytes

12

In [2]:
import numpy as np

In [3]:
c = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])

In [4]:
print(c)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [6]:
c.shape

(2, 7)

In [10]:
# Get a specific element [r, c]
c[1,5]

13

In [14]:
# Get a specific row:
c[1, : ]

array([ 8,  9, 10, 11, 12, 13, 14])

In [15]:
# Get a specific column:
c[ : , 2]

array([ 3, 10])

In [16]:
# Getting a little more fancy [startindex:endindex:stepsize]
c[0, 1:6:2]

array([2, 4, 6])

In [19]:
#Make change to array
c[1,5] = 20
print(c)


[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [29]:
c[ : , 2] = 5
print(c)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [31]:
c[ : , 2] = [1,2]
print(c)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [34]:
#3-d example:
B = np.array([[[1,2],[3,4],[5,6],[7,8]]])
print(B)

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


In [36]:
#Get a specific element (work outside in)
#To get 4 here (first set / second row / second column)
B[0,1,1]

4

In [45]:
#replace 
B[ : ,1, : ] = [[9,9],[8,8]]
print(B)

ValueError: cannot copy sequence with size 2 to array axis with dimension 1

In [47]:
#Initializing Different Types of Arrays

In [ ]:
#All 0s matrix:

In [48]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [50]:
np.zeros((2,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [51]:
#All 1s matrix:
np.ones((4,2,2))


array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [52]:
# Any other number (the first parameter is shape and the second parameter is values)
np.full ((2,2) , 99)


array([[99, 99],
       [99, 99]])

In [56]:
# Any other number (full_like method) (we pass the shape from another variable to make a new variable based on that)
np.full_like(c, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [58]:
# Random decimal number
np.random.rand(4,2)

array([[0.03173028, 0.12368977],
       [0.45799276, 0.11631309],
       [0.77911519, 0.00814681],
       [0.30608917, 0.68661532]])

In [60]:
# random integer values (numbers between 0 to 7)
np.random.randint(7, size=(3,3))


array([[5, 6, 6],
       [2, 5, 3],
       [3, 1, 6]])

In [62]:
# random integer values (numbers between 4 to 7)
np.random.randint(4,7, size=(3,3))

array([[5, 4, 6],
       [4, 5, 6],
       [4, 5, 5]])

In [63]:
#The identity matrix
np.identity(5)


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [65]:
# Repeat an array (3 times here)
a = np.array([1,2,3])
r1 = np.repeat(a,3)
print(r1)


[1 1 1 2 2 2 3 3 3]


In [67]:
# Repeat an array (3 times here) (two dimentsional here)
a = np.array([[1,2,3]])
r1 = np.repeat(a,3, axis=0)
print(r1)


[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [68]:
output = np.ones((5,5))
print(output)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [69]:
z = np.zeros((3,3))
print(z)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [70]:
z [1,1] = 9
print(z)

[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


In [71]:
output[1:4,1:4] = z
print(output)


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [72]:
##### Be careful when copying arrays!!!
a = np.array([1,2,3])
b = a
print(b)


[1 2 3]


In [73]:
b[0] = 100
print(b)


[100   2   3]


In [74]:
print(a)

[100   2   3]


In [77]:
# (As we see above, when we changed an element in b, it was changed in a too)
#in order to prevent that, we could make a copy of a:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(a)

[1 2 3]


In [78]:
#Mathematics
a = np.array([1,2,3,4])
print(a)


[1 2 3 4]


In [79]:
a + 2

array([3, 4, 5, 6])

In [80]:
a - 2

array([-1,  0,  1,  2])

In [81]:
a*2

array([2, 4, 6, 8])

In [82]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [84]:
b = np.array([1,0,1,0])

In [85]:
a + b

array([2, 2, 4, 4])

In [86]:
a ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [87]:
#Take the Sin
np.sin(a)


array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [88]:
#Take the cos
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

Linear Algebra

In [89]:
a = np.ones((2,3))

In [90]:
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [92]:
b=np.full((3,2),2)
print(b)

[[2 2]
 [2 2]
 [2 2]]


In [93]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [94]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)


1.0

Statistics

In [97]:
stats = np.array([[1,2,3],[4,5,6]])
print(stats)

[[1 2 3]
 [4 5 6]]


In [98]:
np.min(stats)

1

In [99]:
np.max(stats)

6

In [101]:
np.min(stats, axis=0)

array([1, 2, 3])

In [103]:
np.max(stats, axis=1)

array([3, 6])

In [104]:
np.sum(stats)

21

In [105]:
np.sum(stats, axis=0)

array([5, 7, 9])

Reorganizing array

In [111]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

[[1 2 3 4]
 [5 6 7 8]]


In [112]:
after = before.reshape((8,1))
print(after)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [115]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])


In [116]:
np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [117]:
np.vstack([v1,v2,v2,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [118]:
# Horizontal stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

In [119]:
print(h1)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [120]:
print(h2)

[[0. 0.]
 [0. 0.]]


In [121]:
np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

Miscellaneous

Load data from file

In [125]:
filedata = np.genfromtxt('name_of_the_file.txt', delimiter=' , ')

OSError: name_of_the_file.txt not found.

In [126]:
### Boolean Masking and Advanced indexing